### ISSUE TITLE
Add a method to register existing objects as dependencies

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#21]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

Sometimes, it's preferable to register an existing object as though it were a dependency. Currently, it has to be wrapped in a `Service`:
```swift
Service(.transient, SomeClass.self) { _ in
    return existingObject
}
```
The closure feels unnecessary, and the choice of scope is completely arbitrary.

## Feature Request

There should be a way to provide the existing object as a constant. I'm not sure what the exact syntax should look like, so I'm open to suggestions here, but I was thinking perhaps something like
```swift
Service.constant(SomeClass.self, existingObject)
```
or
```swift
Service(SomeClass.self, constant: existingObject)
```

## Value

This would result in shorter and less arbitrary code in cases where the object already exists.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by bbrk24** [comment]
This is technically possible with the current implementation of the library, but it's a bit more involved than I feel should be necessary:

```swift
struct ConstantRegistration: Registration {
    let type: Any.Type
    let name: String?
    private let value: Any

    init<T>(
        _ type: T.Type,
        _ name: String? = nil,
        _ value: T
    ) {
        self.type = T.self
        self.name = name
        self.value = value
    }

    func resolve(_: Resolver) -> Any {
        return self.value
    }
}

Factory.register {
    ConstantRegistration(SomeClass.self, existingObject)
}
```

**Comment by wboyd600** [comment]
Yeah, I think this could easily be a part of the library.

**Comment by wboyd600** [comment]
To be honest I can't think of a good way around the problems we've mentioned without making another Registration struct

**Comment by bbrk24** [comment]
No, that's the idea. Just like we have `internal class WeakRegistration`, we'd have an `internal struct ConstantRegistration`. Then there'd be some `Service.init` that wraps around it, just like for the existing three. My only question is what that init should look like.

**Comment by wboyd600** [comment]
Would it be possible to make it like
```
Service(constant: existingObject, SomeClass.self)
```

So at least the `T.Type` parameter ends up in the same place and it's clear it doesn't take a scope?
