### ISSUE TITLE
Extend command line testing to include both example projects

### ISSUE THREAD

**Issue by wboyd600** [Tiny-Home-Consulting/Dependiject#31]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem
When reviewing PRs, one must run the command line tests. One must also open both example projects in XCode to run their tests individually. It would be more efficient if reviewers could run all of the tests from the command line.

## Feature Request
Write a script that executes the Dependiject tests as well as each example project's tests. Ideally, one could run this script with one command and see the results in terminal window.

## Value
This would speed up the pull request review process. This would also reduce human error in the review process, and enforce a greater level of consistency between example projects.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by bbrk24** [comment]
I've investigated this a little, but it seems that `xcodebuild` doesn't run the "Generate Mockingbird Mocks" build phase, at least not by default. I'm not going to spend too much more time on this today, but that's the biggest problem I've encountered.

**Comment by wboyd600** [comment]
Okay, I think the same build phase script could be run from command line as well.

Something like this might work if ran (at some appropriate point) within the script (ignoring file paths):
```
"${SRCROOT}/Pods/MockingbirdFramework/mockingbird" generate --targets "DependijectExample" --outputs "${SRCROOT}/MockingbirdMocks/DependijectExampleTests-DependijectExampleMocks.generated.swift"
```

We can do some more investigation into how other projects setup their CI-CD pipeline for getting the available simulators as well.

**Comment by bbrk24** [comment]
Yeah, I suppose we could duplicate the script, but that's just one more place to change should the Mockingbird script be changed.

**Comment by wboyd600** [comment]
Shouldn't it not change unless we purposefully upgrade to the next major version?

**Comment by bbrk24** [comment]
Possibly. Or it could change because we upgraded minor versions and we want access to newer features. Either way, I'd prefer to avoid code duplication where possible.

**Comment by wboyd600** [comment]
Might it be possible to just invoke the xcode build phase script regardless of what it is?

**Comment by bbrk24** [comment]
It seems like `xcodebuild` doesn't invoke these scripts -- rather, Xcode runs them before building. We could extract the script to its own file and then have both the test runner and the run script phase invoke that file.

**Comment by bbrk24** [comment]
Scratch that, I got `xcodebuild` to run the scripts. It turns out the dependencies in the xcworkspace were wrong.
