### ISSUE TITLE
Add type-safe overload of MultitypeService.init

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#41]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

`MultitypeService` is impossible to type-check at compile time. Currently, it is enforced with `as!` at resolution time; however, in limited cases it may be possible to enforce it at registration time.

## Feature Request

Add an overload for `MultitypeService.init` along the lines of

```swift
init(exposedAs protocols: [Protocol], _ value: T)
where T: NSObjectProtocol {
    assert(protocols.allSatisfy { value.conforms(to: $0) })
    // ...
}
```

or perhaps

```swift
init(classes: [AnyClass] = [], protocols: [Protocol], _ value: T)
where T: NSObjectProtocol {
    assert(protocols.allSatisfy { value.conforms(to: $0) })
    assert(classes.allSatisfy { value.isKind(of: $0) })
    // ...
}
```

~~The fact that `Protocol` is not convertible to/from `Any.Type` means that this will have far-reaching, potentially undesirable effects on the entire library.~~ Update: see [this StackOverflow post](https://stackoverflow.com/a/73914279/)

## Value

This issue is mostly a placeholder, as the underlying problem is low-priority. This can be investigated further if/when desired.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by bbrk24** [comment]
Potential implementation:
```swift
    public init(enforcing types: [Any.Type], for value: T)
    where T: NSObject {
        for type in types {
            if let c = type as? AnyClass {
                precondition(value.isKind(of: c), "Given value does not belong to class \(type)")
            } else if let p = type as AnyObject as? Protocol {
                precondition(value.conforms(to: p), "Given value does not adopt protocol \(type)")
            } else {
                preconditionFailure(
                    "\(#function) can only be called with classes and @objc protocols, not \(type)"
                )
            }
        }
        
        self.init(exposedAs: types, value)
    }
```

**Comment by wboyd600** [comment]
I feel like we're really limited by the protocol needing to be `@objc` protocols and it still wouldn't be checked at compile time.
