### ISSUE TITLE
Add warning when MultitypeService receives empty array

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#49]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

If MultitypeService receives an empty array for the `exposedAs:` argument, it is impossible to resolve the dependency.

## Feature Request

Add some kind of warning or error that is triggered when the exposed types array is empty.

## Value

As these dependencies cannot be resolved anyways, their presence is likely a mistake.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by wboyd600** [comment]
It would be nice if this could be a compile time warning but that would probably pose some difficulties. I don't think we'd want it as an assert because that would just be annoying during development

**Comment by bbrk24** [comment]
Naturally, you can't check the length of an array at compile-time. Swift errors when an integer is out of bounds, and you can get special compile-time string semantics with the `StaticString` type, but arrays are always constructed at runtime. The best thing I can think of is a `print` statement, but that's so easy to miss it almost doesn't feel worth it.

**Comment by wboyd600** [comment]
Yeah, it really doesn't (feel worth it). You'd become aware of the issue as soon as you tried to resolve an unexposed type as well.
