### ISSUE TITLE
Named MultitypeService

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#56]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

There is no way to disambiguate services registered under `MultitypeService` when the types overlap.

## Feature Request

There are three different ways I could see this manifesting:
1. The service as a whole has a name
```swift
MultitypeService(exposedAs: [...], name: "service name") { ... }
```
2. Each individual type has a name
```swift
MultitypeService(exposedAs: [
  (type: Foo.self, name: "named foo")
  (type: Bar.self, name: "named bar")
]) { ... }
```
3. Only some types are named. I'm not sure what the interface for this would look like. I suppose this could be done with the same interface as the previous.

## Value

Regular services can already be named, and there's no reason that MultitypeService couldn't.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by wboyd600** [comment]
I feel like the custom type with optional parameters would make naming and not naming looking the best

**Comment by bbrk24** [comment]
There's no reason we can't support both:
```swift
init(exposedAs types: [Any.Type], name: String? = nil, callback: @escaping (Resolver) -> T)
init(exposedAs interfaces: [(type: Any.Type, name: String?)], callback: @escaping (Resolver) -> T)
```

**Comment by wboyd600** [comment]
Hmm, yeah I guess flexibility would be the most desirable trait here. I think it makes sense to support both. I imagine it would make `MultitypeService` a bit more complicated so we'll have to be thorough in testing, but that is always the case. At least the `resolve` part of it should stay the same.
