### ISSUE TITLE
Changes are sometimes published late by default

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#62]
## Checklist

- [x] I updated to the latest version and the problem persists.
- [x] I searched the [existing GitHub issues][1] and this hasn't already been reported.

## Overview

A ScrollView blocks the main run loop, but not the main dispatch queue. This means that changes published on RunLoop.main (the default) are not received until after the user finishes scrolling, while changes published on DispatchQueue.main (a different wrapper around the main thread) are published instantly.

## Example Reproduction

```swift
class ViewModel: ObservableObject, AnyObservableObject {
    @Published var thing = "foo"
}

struct ExampleView: View {
    @Store var viewModel = ViewModel()

    var body: some View {
        VStack {
            Button("Change text") { viewModel.thing = "bar" }

            ScrollView {
                VStack {
                    ForEach(0..<100) { _ in Text(viewModel.thing) }
                }
            }
        }
    }
}
```

## Behavior

Currently, if the button is clicked while the scroll view is scrolling, the text does not change until the scroll stops. If the property wrapper is changed to `@Store(on: DispatchQueue.main)`, the text changes as soon as the button is pressed.

## Environment

| Software    | Version |
|:------------|:--------|
| macOS       | `12.6.0` |
| Xcode       | `14.0.1` |
| Dependiject | `0.3.0` |
| CocoaPods   | `1.11.3` |

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by wboyd600** [comment]
Yeah, I just read through this [article](https://www.avanderlee.com/combine/runloop-main-vs-dispatchqueue-main/). It's basically saying the only reason to ever use the main run loop is if you want desire this behavior. The natural conclusion is while there is a reason someone might want to schedule on the main run loop, we should default to `DispatchQueue.main`
