### ISSUE TITLE
Mutating Factory.options

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#65]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested. -- Though it relates to #35

## Problem

It is currently not possible to mutate `Factory.options` in a thread-safe way, and operations like `Factory.options.maxDepth += 1` are not atomic. Every access to the property will generate a warning with `-warn-concurrency` or in Swift 6.

## Feature Request

I think the best way to do this is to provide a method such as `mutateOptions(mutation: (inout ResolutionOptions) throws -> Void) rethrows`. This is better than a setter function because it discourages the following code:
```swift
var options = Factory.getOptions()
options.maxDepth += 1
Factory.setOptions(options)
```
A potential implementation of this could look like:
```swift
private var options = ResolutionOptions()

public func getOptions() -> ResolutionOptions {
    lock.lock()
    defer {
        lock.unlock()
    }
    return options
}

public func modifyOptions(mutation: (inout ResolutionOptions) throws -> Void) rethrows {
    lock.lock()
    defer {
        lock.unlock()
    }
    try mutation(&options)
}
```
The stored property is intentionally not `static`, to avoid the concurrency warnings mentioned above. There's little functional difference, but once it's marked as `static var` it's suddenly "shared mutable state" and every access produces a warning (with `-warn-concurrency` or in Swift 6). The methods could be static, like `register(builder:)` and `clearDependencies()`; I'm willing to do those either way.

Conversely, the lock could be `static`, but that isn't necessary for this feature.

## Value

The README says:

> Dependiject provides simple, flexible, and thread-safe dependency injection for testability and inversion of control in SwiftUI apps.

Currently, setting the factory's options is not thread-safe. With this change, it would be.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by Ljgleeson** [comment]
I agree that the suggested implementation you provided above would work and is also consistent with how we handle thread-safety in the other Factory functions.

**Comment by wboyd600** [comment]
Good with me
