### ISSUE TITLE
Obscure or document MultitypeService.Iterator

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#66]
## Checklist

- [x] I searched the [existing GitHub issues][1] and this hasn't already been requested.

## Problem

Currently, MultitypeService contains the following line:
```swift
public typealias Iterator = Array<Registration>.Iterator
```
This is exposing an implementation detail the clients don't need to know about. In theory, someone could rely on the fact that this is `IndexingIterator<[Registration]>`, in which case changes to what should be the implementation instead become breaking changes.

## Feature Request

There's multiple ways to fix this, and I'm not sure which one is best.
- Document that it returns `IndexingIterator<[Registration]>`, so it's part of the public API rather than an exposed implementation detail
- Document that it is `IndexingIterator`, but not what the base type is, i.e. `IndexingIterator<some Collection<Registration>>`
  - This would require bumping the minimum Swift version to 5.7.1\*
- Obscure the underlying type using `some IteratorProtocol<Registration>` or `some IteratorProtocol<Registration> & Sequence<Registration>`
  - This also requires Swift 5.7.1\*
- Hide the underlying iterator type, and wrap the return value in `AnyIterator`.

I'm leaning towards either the first or last option, so as not to necessitate the change in the required Swift version.

\*Technically, this could work on iOS, watchOS, and tvOS in Swift 5.7.0. However, on macOS, protocols from the standard library aren't generic until Swift 5.7.1.

## Value

This isn't strictly needed, but without this, changes that were intended to be implementation-only could instead be source-breaking.

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

**Comment by Ljgleeson** [comment]
I agree that we shouldn't have to change the required swift version and between the first and the last option I'm leaning towards hiding the underlying iterator type. My concern with the first option is if the client doesn't need to know about this then the solution to publicly document it doesn't really fix the problem but rather just clears the ambiguity behind it being exposed.

**Comment by wboyd600** [comment]
I vote for hide it
