### ISSUE TITLE
Switching over enums

### ISSUE THREAD

**Issue by bbrk24** [Tiny-Home-Consulting/Dependiject#67]
This isn't necessarily a problem, but it is a discussion we need to have before releasing v1.0.

Note: Though I only mention `ErrorCheckMode` throughout this issue, the same arguments also apply to `Scope`, as well as any new enums we may add in a future version.

---

Currently, it's possible for a user of the library to write code like the following:
```swift
switch Factory.options.mode {
case .never: // ...
case .debugOnly: // ...
case .always: // ...
}
```
Then, adding new cases to the `ErrorCheckMode` enum is a source-breaking change. There are a few different ways to solve this:
- Just accept it. Only add new enum cases in major versions (1.0, 2.0 etc).
- Add a `.reserved(Int)` case. Then, adding "new cases" becomes  
  ```swift
  static let newCase1 = ErrorCheckMode.reserved(1)
  static let newCase2 = ErrorCheckMode.reserved(2)
  ```  
  This has a downside in its own right: if the user sets the error check mode to `.reserved(3)`, and we haven't defined that yet, how should we handle the mismatch?
- Hide the enums behind a struct. This is the most flexible method, but it also requires the most boilerplate:
  ```swift
  struct ErrorCheckMode: Equatable {
      internal let value: UnderlyingType

      public static let never = ErrorCheckMode(value: .never)
      public static let debugOnly = ErrorCheckMode(value: .debugOnly)
      public static let always = ErrorCheckMode(value: .always)

      internal enum UnderlyingType: Equatable {
          case never, debugOnly, always
      }
  }
  ```
  Using a struct like this requires the user to write a `default:` in the switch statement, preventing source breakage from adding a new case. Swift guarantees that a struct with only one stored property has the same memory layout as that stored property, so (unlike `.reserved(_:)`) this adds no memory overhead.  
  Declaring the underlying enum as `internal` instead of `private` means that we can `switch mode.value` within the library, which in turn means we won't need an unreachable `default` branch.

---

I'd like to hear feedback on whether this is even a problem, and if so how best to solve it.

**Comment by wboyd600** [comment]
The only other case I can think of for the debug mode is `productionOnly` which doesn't really seem necessary. For the scope though, I wouldn't be entirely surprised if we wanted to add another but I'm not sure how we'd want to handle that.

**Comment by bbrk24** [comment]
It's also good to keep in mind that, in the future, if we add any more enums, the same problems will apply there as well.

I think it's perfectly reasonable to apply different policies to different enums -- e.g. "don't add cases" for ErrorCheckMode but "wrap it in a struct" for Scope.

**Comment by Ljgleeson** [comment]
I think applying different policies to different enums would be the best course of action here so we don't have to wait for major releases to add any more enum cases down the line.
